---
- name: Generate WireGuard client private key {{ client_key_number }} for VPN {{ vpn_number }} 
  ansible.builtin.command: "wg genkey"
  register: wireguard_client_private_key
  changed_when: false
  tags: [client_keys_generation,vpn_installation]

- name: Set facts with client private key {{ client_key_number }} for VPN {{ vpn_number }} 
  set_fact:
    client_private_keys: "{{ client_private_keys | default({}) | combine ({ 'vpn' ~ vpn_number ~ 'key' ~ client_key_number : wireguard_client_private_key.stdout }) }}"
  tags: [client_keys_generation,vpn_installation]

- name: Generate WireGuard client public key {{ client_key_number }} for VPN {{ vpn_number }} 
  ansible.builtin.command: "wg pubkey"
  args:
    stdin: "{{ client_private_keys['vpn' ~ vpn_number ~ 'key' ~ client_key_number] }}"
  register: wireguard_client_public_key
  changed_when: false
  tags: [client_keys_generation,vpn_installation]

- name: Set facts with client public key {{ client_key_number }} for VPN {{ vpn_number }} 
  set_fact:
    client_public_keys: "{{ client_public_keys | default({}) | combine ({ 'vpn' ~ vpn_number ~ 'key' ~ client_key_number : wireguard_client_public_key.stdout }) }}"
  tags: [client_keys_generation,vpn_installation]

- name: Generate WireGuard preshared key {{ client_key_number }} for VPN {{ vpn_number }} 
  ansible.builtin.command: "wg genpsk"
  register: wireguard_client_preshared_key
  changed_when: false
  tags: [client_keys_generation,vpn_installation]

- name: Set facts with client preshared key {{ client_key_number }} for VPN {{ vpn_number }} 
  set_fact:
    client_preshared_keys: "{{ client_preshared_keys | default({}) | combine ({ 'vpn' ~ vpn_number ~ 'key' ~ client_key_number : wireguard_client_preshared_key.stdout }) }}"
  tags: [client_keys_generation,vpn_installation]