---
# tasks file for vpn_installation
- name: Install WireGuard packages
  apt:
    name:
      - wireguard-tools
      - wireguard
      - qrencode
    state: present
    update_cache: true
  tags: [vpn_installation]

- name: Remove WireGuard clients remote directory
  file:
    path: /etc/wireguard/clients
    state: absent
  tags: [add_vpn,vpn_installation]

- name: Remove WireGuard clients local directory
  file:
    path: clients
    state: absent
  become: false
  delegate_to: localhost
  tags: [add_vpn,vpn_installation]

- name: Create WireGuard clients remote directory
  file:
    path: /etc/wireguard/clients
    state: directory
    mode: 0700
  tags: [add_vpn,vpn_installation]

- name: Create WireGuard clients local directory
  file:
    path: clients
    state: directory
    mode: 0700
  become: false
  delegate_to: localhost
  tags: [add_vpn,vpn_installation]

- name: Generate VPN interface
  include_tasks: add_vpn.yml
  loop: "{{ range(0, number_of_vpns) | list }}"
  loop_control:
    loop_var: vpn_number
  tags: [vpn_installation]

- name: Allow WireGuard traffic on specified ports for multiple VPNs
  iptables:
    table: filter
    chain: INPUT
    in_interface: "{{ ansible_default_ipv4.interface }}"
    protocol: udp
    state: present
    destination_ports: "{{ vpn_listen_port_base}}0:{{ vpn_listen_port_base}}{{ number_of_vpns - 1 }}"
    jump: ACCEPT
  when: number_of_vpns > 1
  tags: [vpn_installation]

- name: Allow WireGuard traffic on specified port for single VPN
  iptables:
    table: filter
    chain: INPUT
    in_interface: "{{ ansible_default_ipv4.interface }}"
    protocol: udp
    state: present
    destination_port: "{{ vpn_listen_port_base}}0"
    jump: ACCEPT
  when: number_of_vpns == 1
  tags: [vpn_installation]

- name: Find new generated client configs for VPNs
  ansible.builtin.find:
    paths: /etc/wireguard/clients
    recurse: yes
  register: files_to_copy
  tags: [vpn_installation]

- name: Fetch new clients configs to localhost for VPNs
  ansible.builtin.fetch:
    src: "{{ item }}"
    dest: clients
    mode: 644
  with_items: "{{ files_to_copy.files | map(attribute='path') | list }}"
  tags: [vpn_installation]
